### ISSUE TITLE
Add progress return value to useDownload hook

### ISSUE THREAD

**Issue by bryandms** [novajslabs/nova.js#103]
### Description

I wanna add a new return value to the `useDownload` hook, which allows knowing the percentage or progress of the download (If the response has the header content-length).

### Example

https://github.com/user-attachments/assets/b87dc019-f7f2-4103-a0a1-d634f7da0e97

I prefer to name it `progress` or `downloadProgress`, but if you think there is a better semantic name I'm open to suggestions and feedback to improve the proposal.

**Comment by dlcastillop** [comment]
I love the idea. Consider the following:

- Use the name `progress` for the return value
- `progress` will be a number (the percentage ) or null if the response has not the header content-length

I already assigned the issue to you. Thank you!
