### ISSUE TITLE
New hook to detect if the device is touch-enabled

### ISSUE THREAD

**Issue by uvee-dev** [novajslabs/nova.js#42]
### Description
Currently, Nova.js lacks a hook to detect whether the device is touch-enabled or not. This could be useful for adapting the user interface or application behavior based on the device type.

### Proposed new feature
I propose adding a new hook called useIsTouchDevice to detect if the device is touch-enabled. This hook will utilize standard methods to determine this condition.

**Comment by dlcastillop** [comment]
@uvee-dev do you want to develop this hook?

**Comment by dlcastillop** [comment]
@uvee-dev I just assigned the issue to you. If you have any questions just make a comment. I will answer it as soon as possible.
